!!python/object:model_diffing.scripts.train_l1_crosscoder.config.TrainConfig
__dict__:
  batch_size: 4096
  lambda_max: 5.0
  lambda_n_steps: 1000
  learning_rate: !!python/object:model_diffing.scripts.train_l1_crosscoder.config.DecayTo0LearningRateConfig
    __dict__:
      initial_learning_rate: 5.0e-05
      last_pct_of_steps: 0.2
    __pydantic_extra__: null
    __pydantic_fields_set__: !!set
      initial_learning_rate: null
      last_pct_of_steps: null
    __pydantic_private__: null
  log_every_n_steps: 50
  n_batches_for_norm_estimate: 100
  num_steps: 100000
  save_dir: !!python/object/apply:pathlib.PosixPath
  - checkpoints
  - l1_crosscoder
  save_every_n_steps: 250
__pydantic_extra__: null
__pydantic_fields_set__: !!set
  batch_size: null
  lambda_max: null
  lambda_n_steps: null
  learning_rate: null
  log_every_n_steps: null
  num_steps: null
  save_dir: null
  save_every_n_steps: null
__pydantic_private__: null
