data:
  sequence_iterator:
    classname: HuggingfaceTextDatasetTokenSequenceLoader
    kwargs:
      hf_dataset_name: "monology/pile-uncopyrighted"
      sequence_length: 256
      shuffle_buffer_size: 16_384
  activations_harvester:
    llms:
      - name: EleutherAI/pythia-160M
        revision: step142000
      - name: EleutherAI/pythia-160M
        revision: step143000
    layer_indices_to_harvest: [8]
    harvesting_batch_size: 32
  activations_shuffle_buffer_size: 16_384
  token_window_size: 2
crosscoder:
  hidden_dim: 6144
train:
  batch_size: 32
  optimizer:
    warmup_pct: 0.05
    initial_learning_rate: 4e-4
    last_pct_of_steps: 0.2
  num_steps: 30_000
  save_every_n_steps: 500
  log_every_n_steps: 50

experiment_name: test
wandb: true