data:
  token_sequence_loader:
    type: HuggingfaceTextDatasetTokenSequenceLoader
    hf_dataset_name: "monology/pile-uncopyrighted"
    sequence_length: 2048
  activations_harvester:
    llms:
      - name: EleutherAI/pythia-160M
        revision: step143000 # last checkpoint
    harvesting_batch_size: 32
crosscoder:
  hidden_dim: 4096
train:
  num_steps: 20_000
  batch_size: 65_536
  gradient_accumulation_steps_per_batch: 16  # for a minibatch size of 4096
  save_every_n_steps: 2500
  log_every_n_steps: 20
  final_lambda_s: 5.0
  lambda_s_n_steps: 20_000
experiment_name: oli_l1_sliding_window
hookpoints:
  - "blocks.0.hook_resid_post"
  - "blocks.1.hook_resid_post"
  - "blocks.2.hook_resid_post"
  - "blocks.3.hook_resid_post"