seed: 42
dtype: float32
models:
  - name: EleutherAI/pythia-160M
    revision: step3000
  - name: EleutherAI/pythia-160M
    revision: step4000
layer_indices_to_harvest:
  - 2
  - 6
  - 10
dataset:
  hf_dataset: PleIAs/common_corpus
  sequence_length: 256
  cache_dir: ".cache"
  harvest_batch_size: 8
  shuffle_buffer_size: 16384
crosscoder:
  hidden_dim: 6144
train:
  lr: 5e-5
  lambda_max: 5
  lambda_n_steps: 1000
  batch_size: 4096
  steps: 10_000
  save_dir: './checkpoints/crosscoder'
  save_every_n_steps: 1000
  log_every_n_steps: 50
wandb:
#   project: model-diffing
#   entity: oliclive-griffin  # TODO: change this

