data:
  token_sequence_loader:
    type: HuggingfaceTextDatasetTokenSequenceLoader
    hf_dataset_name: "monology/pile-uncopyrighted"
    sequence_length: 256
  activations_harvester:
    llms:
      - name: EleutherAI/pythia-160M
        revision: step143000 # last checkpoint
    harvesting_batch_size: 1
crosscoder:
  hidden_dim: 4096
  jumprelu:
    backprop_through_jumprelu_input: true
  initial_approx_firing_pct: 0.5 # WARNING(oli): very uncertain this is a good default!
train:
  optimizer:
    type: adam
    learning_rate: 0.001
  num_steps: 10_000
  batch_size: 32
  save_every_n_steps: 2500
  log_every_n_steps: 50
  c: 4.0
  final_lambda_s: 5.0
  lambda_p: 0.000003 # 3e-6
experiment_name: sliding_window_test
hookpoints:
  - "blocks.0.hook_resid_post"
  - "blocks.1.hook_resid_post"
  - "blocks.2.hook_resid_post"