data:
  sequence_iterator:
    classname: HuggingfaceTextDatasetTokenSequenceLoader
    kwargs:
      hf_dataset_name: "monology/pile-uncopyrighted"
      sequence_length: 256
      shuffle_buffer_size: 16_384
  activations_harvester:
    llms:
      - name: EleutherAI/pythia-160M
        revision: step142000
      - name: EleutherAI/pythia-160M
        revision: step143000 # last checkpoint
    layer_indices_to_harvest: [2]
    harvesting_batch_size: 32
  activations_shuffle_buffer_size: 8_192
crosscoder:
  hidden_dim: 6144
train:
  batch_size: 32
  optimizer:
    initial_learning_rate: 5e-5
    last_pct_of_steps: 0.2
  lambda_s_max: 5
  lambda_s_n_steps: 1000
  num_steps: 10_000
  save_every_n_steps: 1000
  log_every_n_steps: 20
experiment_name: l1_crosscoder_pythia_160M_layer_2
wandb: True