data:
  sequence_iterator:
    classname: HuggingfaceTextDatasetTokenSequenceLoader
    kwargs:
      hf_dataset_name: "monology/pile-uncopyrighted"
      sequence_length: 256
      shuffle_buffer_size: 8192
  activations_harvester:
    llms:
      - name: EleutherAI/pythia-160M
        revision: step142000
      - name: EleutherAI/pythia-160M
        revision: step143000 # last checkpoint
    harvesting_batch_size: 1
  activations_shuffle_buffer_size: 2048
crosscoder:
  hidden_dim: 6144
train:
  num_steps: 10_000
  batch_size: 32
  save_every_n_steps: 2500
  log_every_n_steps: 100
  lambda_s_max: 5
  lambda_s_n_steps: 1000
  save_every_n_steps: 1000
  log_every_n_steps: 20
experiment_name: l1_crosscoder_example
hookpoints: ["blocks.8.hook_resid_post"]