data:
  sequence_iterator:
    classname: CommonCorpusTokenSequenceIterator
    kwargs:
      sequence_length: 256
  sequence_shuffle_buffer_size: 16_384
  activations_harvester:
    layer_indices_to_harvest: [2]
    harvest_batch_size: 16
  activations_shuffle_buffer_size: 8_192
  cc_training_batch_size: 512
llms:
  models:
    - name: EleutherAI/pythia-160M
      revision: step142000
    - name: EleutherAI/pythia-160M
      revision: step143000 # last checkpoint
wandb:
  name: l1_crosscoder_pythia_160M_layer_3
crosscoder:
  hidden_dim: 6144
train:
  optimizer:
    initial_learning_rate: 5e-5
    last_pct_of_steps: 0.2
  l1_coef_max: 5
  l1_coef_n_steps: 1000
  num_steps: 10_000
  save_dir: './.checkpoints/l1_crosscoder_pythia_160M_layer_3'
  save_every_n_steps: 1000
  log_every_n_steps: 20
  log_visualizations_every_n_steps: 1000
