seed: 42
dtype: float32
models:
  - name: EleutherAI/pythia-160M
    revision: step142000
  - name: EleutherAI/pythia-160M
    revision: step143000 # last checkpoint
layer_indices_to_harvest:
  - 8
dataset:
  hf_dataset: PleIAs/common_corpus
  cache_dir: ".cache"
  sequence_length: 256
  harvest_batch_size: 8
  shuffle_buffer_size: 16384
crosscoder:
  hidden_dim: 6144
train:
  lr: 5e-5
  lambda_max: 5
  lambda_n_steps: 1000
  batch_size: 4096
  epochs: 1
  save_dir: './checkpoints/crosscoder'
  save_every_n_epochs: 1
  log_every_n_steps: 50
wandb:
  project: model-diffing
  entity: mars-model-diffing

