data:
  token_sequence_loader:
    type: MathDatasetTokenSequenceLoader
    max_sequence_length: 2048
    include_base_answers: true
    include_reasoning_answers: true
  activations_harvester:
    llms:
      - base_archicteture_name: Qwen/Qwen2.5-1.5B
        hf_model_name: Qwen/Qwen2.5-Math-1.5B
      - base_archicteture_name: Qwen/Qwen2.5-1.5B
        hf_model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
    harvesting_batch_size: 16
    inference_dtype: bfloat16
  n_tokens_for_norm_estimate: 100_000
crosscoder:
  hidden_dim: 32_768
  n_shared_latents: 2048 # 1/16 explicitly shared latents
  jumprelu:
    backprop_through_jumprelu_input: true
  initial_approx_firing_pct: 0.2
  n_tokens_for_threshold_setting: 40_000
train:
  num_steps: 10_000
  batch_size: 16_384
  gradient_accumulation_steps_per_batch: 2 # for a minibatch size of 8192
  save_every_n_steps: 1000
  log_every_n_steps: 8
  c: 4.0
  final_lambda_s: 10.0
  final_lambda_f: 50.0
  lambda_p: 0.000003
experiment_name: math-rl-test
hookpoint: "blocks.20.hook_resid_post"