data:
  sequence_iterator:
    classname: HuggingfaceTextDatasetTokenSequenceLoader
    kwargs:
      hf_dataset_name: "monology/pile-uncopyrighted"
      sequence_length: 2048
      shuffle_buffer_size: 8192
  activations_harvester:
    llms:
      - name: EleutherAI/pythia-160M
        revision: step142000
      - name: EleutherAI/pythia-160M
        revision: step143000 # last checkpoint
    harvesting_batch_size: 8
  activations_shuffle_buffer_size: 32_768
crosscoder:
  hidden_dim: 16_384
  k: 32
train:
  num_steps: 50_000
  batch_size: 2048
  save_every_n_steps: 2500
  log_every_n_steps: 50
experiment_name: skip_trans_crosscoder_example
mlp_indices: [7]