seed: 0
model_names:
  - google/gemma-2b
  - google/gemma-2b-it
layer_indices_to_harvest:
  - 2
  - 6
  - 10
  - 14
dataset:
  hf_dataset: PleIAs/common_corpus
  sequence_length: 256
  cache_dir: null
  harvest_batch_size: 16
  shuffle_buffer_size: 1024
crosscoder:
  hidden_dim: 4096
train:
  lr: 5e-5
  lambda_max: 5.0
  lambda_n_steps: 1000
  batch_size: 128
  epochs: 15
  save_dir: './checkpoints/crosscoder'
  save_every_n_epochs: 1
wandb:
  project: model-diffing
  entity: oliclive-griffin  # TODO: change this

