data:
  sequence_iterator:
    batch_size: 16
    classname: SleeperTokenSequenceLoader
    kwargs:
      include_sleeper_data: false
      sequence_length: 128
      shuffle_buffer_size: 1024
  activations_harvester:
    layer_indices_to_harvest: [0, 1, 2, 3]
    harvest_batch_size: 16
    llms:
      - name: "roneneldan/TinyStories-Instruct-33M"
        lora_name: "mars-jason-25/tiny-stories-33M-sleepy2"
  activations_shuffle_buffer_size: 1024
  cc_training_batch_size: 256
wandb: true
experiment_name: "crosscoder_M"
crosscoder:
  hidden_dim: 1536
  k: 20
  ft_init_checkpt_folder: "./.checkpoints/crosscoder_S/wandb_checkpoints"
  ft_init_checkpt_epoch: 19
train:
  optimizer:
    initial_learning_rate: 2.5e-5
    last_pct_of_steps: 0.2
  epochs: 3
  base_save_dir: './.checkpoints'
  save_every_n_epochs: 1
  log_every_n_steps: 50
  num_test_batches: 10
  n_batches_for_norm_estimate: 100
  upload_checkpoint_to_wandb_every_n_epochs: 1