data:
  sequence_iterator:
    type: 
    max_sequence_length: 1024
  activations_harvester:
    llms:
      - base_archicteture_name: Qwen/Qwen2.5-1.5B
        hf_model_name: Qwen/Qwen2.5-Math-1.5B
      - base_archicteture_name: Qwen/Qwen2.5-1.5B
        hf_model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
    harvesting_batch_size: 16
    cache_mode: "no_cache"
  n_tokens_for_norm_estimate: 100_000
crosscoder:
  hidden_dim: 16_384
  jumprelu:
    backprop_through_jumprelu_input: true
  initial_approx_firing_pct: 0.3 # WARNING(oli): very uncertain this is a good default!
train:
  optimizer:
    type: adam
    learning_rate: 0.00005
    betas: [0.0, 0.999]
  num_steps: 10_000
  batch_size: 65_536
  gradient_accumulation_steps_per_batch: 16  # minibatch size: 4096
  log_every_n_steps: 16
  save_every_n_steps: 300
  c: 4.0
  final_lambda_s: 2.0
  lambda_p: 0.000003
experiment_name: oli-RL-math-v3
hookpoints: ["blocks.16.hook_resid_post"]
